### ISSUE TITLE
name = new Personnage

### ISSUE THREAD

**Issue by LiaOkami** [colombbus/declick-client#2]
This wrong syntax is working instead 
name = new Personnage()

name.avancer is validated by the commandline

Old issue from tangara-client by @Neonunux.
https://github.com/colombbus/tangara-client/issues/10

**Comment by Yovar** [comment]
`personnage = new Personnage`
`personnage = new Personnage()`
`personnage.avancer`
`personnage.avancer()`

These 4 lines are valid JavaScript statements. They might provoke an error in someone's code logic but it's the user who made a mistake, not the interpreter.

This application is made for beginners so it might be a common mistake, changes will come soon in order to give more hints and alert the user for potential errors in the code editor.
